### ISSUE TITLE
对象字段过多导致上传rap2超时

### ISSUE THREAD

**Issue by quicksandznzn** [jetplugins/yapix#8]
见标题

**Comment by quicksandznzn** [comment]
io.yapix.base.sdk.rap2.Rap2Exception: Read timed out
		at io.yapix.base.sdk.rap2.AbstractClient.execute(AbstractClient.java:92)
		at io.yapix.base.sdk.rap2.AbstractClient.doRequest(AbstractClient.java:54)
		at io.yapix.base.sdk.rap2.Rap2Client.requestPost(Rap2Client.java:241)
		at io.yapix.base.sdk.rap2.Rap2Client.updateInterfaceProperties(Rap2Client.java:221)
		at io.yapix.process.rap2.process.Rap2Uploader.upload(Rap2Uploader.java:71)
		at io.yapix.process.rap2.Rap2UploadAction.lambda$handle$0(Rap2UploadAction.java:50)
		at io.yapix.action.AbstractionUploadAction$1.lambda$run$0(AbstractionUploadAction.java:69)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
		at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
		at java.base/java.lang.Thread.run(Thread.java:829)
		Caused by: java.net.SocketTimeoutException: Read timed out

**Comment by lkqm** [comment]
有几个地方需要提供下：

**Comment by lkqm** [comment]
需要你确认或提供下几个信息:
1. 提供下插件版本
1. 是否确认是因为对象字段过多导致的超时？
2. 如果方便，可以提供下对应的实体模型代码 (小心代码泄露)

**Comment by quicksandznzn** [comment]
> 需要你确认或提供下几个信息:
> 
> 1. 提供下插件版本
> 2. 是否确认是因为对象字段过多导致的超时？
> 3. 如果方便，可以提供下对应的实体模型代码 (小心代码泄露)

版本0.7.1 确定因为对象字段过多导致 减少字段可以上传成功

**Comment by quicksandznzn** [comment]
> 需要你确认或提供下几个信息:
> 
> 1. 提供下插件版本
> 2. 是否确认是因为对象字段过多导致的超时？
> 3. 如果方便，可以提供下对应的实体模型代码 (小心代码泄露)

版本0.7.1   确定是字段过多引起的

**Comment by lkqm** [comment]
目前网络超时间是5秒，后续修复延长下超时至15s，谢谢

**Comment by quicksandznzn** [comment]
respect !

**Comment by lkqm** [comment]
0.8版本已经支持，待插件商店审核通过后可下载，也可以通过release离线下载安装。
